version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements-docs.txt
    # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
